language: python
python:
  - 3.6
env:
  secure: "Ntp8u8TsUVC3ZtAggnCNzZsOEeOCxL6NGit6kt1Be/k6wD2FDaM1xhEBl7rF7KWO1pwrY1JgYve6S3UsxppGnhMWuX64AbfiUqBY9KCZ2zvtAFH2cQC/srrsF83KGurYfP9iiZnlc53KzAkTVbzoI97nQX9VgR/D48C7s6LwzpCoBG9B0JKJ25EbogIy2wWZKUErkhBaSnph8nvew8X76lekUlfiau88bAuSGFWBlR3NYraWzakB4N5IBK2YLBMcmBNh6XW1sbR3RZzwfHZMZYFrfPABjQnE1RS6tXkBoKS2VwtohOR1C2tQJF7T2sA/tv2zM+8lVFUlLwsmpHMUyl4kvpEw8QYjorVhv3zUl4tt8xbnQqNtswpae0vU/+LVh8PAIWAy2I0YTdaCFFOZWViMH03zFrl9vLwDoC8fH59RCFfc2wbKCkRCLXrVUXa9yHBKWk214OBvf36gXp2zir+fj22pTozhu7fjwJsLNn7a4ZddWUxd9/Z+p8JNK//RrECDANMTEb0eRGVQg1f/yExh7Yg8BBh1ZUyhO0DGj4sA9tq+cGjx/LX5dc2WJVgTUorSn1eW+fHkS6rAD34fpCNLdKm1e2ustwJj7nP3cHtEBs/eeqNELRbtx2LEI14iaxF9DMIaonnORxj/3mnwMxt2Ze5cbpl/Gqr627dA9y8="
install:
  - pip install -r requirements.txt
script:
  -  nosetests -v
deploy:
  provider: pypi
  user: lssoftware
  password:
    secure: "ncqUFUf9T+Mc8xCA1kb2YSHk8wK1DVTCHfpokZWZ7uVjIoZiHosZfitPA7MFsyWbeYfgZGhdRvk8WsStBujPtvVTRTSaRKWNLuz90bdb/BUwrjH079jYHRDuDp6qonOYIysn4PvXPoSrOw6hZGNGzV1GU7QAWuiLpVqBc0Zoepfi7AG7lAeM2WYNBW1KAEd91O+WGYI8PfH66ULH2a50eO2TdMGbUEu3SGJwgI4/D7SxBVM114OC80sgjG1+eX/8giK1Fy2S2dwvKKE09h601G8Ia+7YB05VNyX1Sye/27cPnfJs43cMF5NCCgmskghzpqXfhLE0EDDtqr+5hrmpQWlN6/4+6xa0VtjQC7sgeMIYnIlFT08fOSdokpV891iOVAMR/YbR6YVz0LRcEXU85qrm4yezkSpEUb70EFC96QJcnFXkXCHi31IrnWq+C8jln2pjT3Y9B2jlDekNbH9MKjeEIZzcqrpq4akq38I65Yqi76FViMERqjVBfE/97XoIsn3TZvKogqynNdC3b6UWSdbwD7lKglK+emZa0q8nDB2DKR3daYv8BVT+HL1KuuCbZRhKIWeG71L2sDK76gN4HZO8/Lf4TjBDg1TybBW168CXYAuppMulDGIjTPgBmvj+a4WMiROhiNQDjE31zK9xE40VtegzjOhOzVWFeoAarXw="
  on:
    tags: true